# Q1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
x=np.empty((3,3,3))
x

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [7.56597770e-307, 1.89146896e-307, 1.37961302e-306],
        [6.23053614e-307, 6.23053954e-307, 9.34609790e-307]],

       [[8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
        [6.23061763e-307, 9.34608432e-307, 1.86921007e-306],
        [7.56596412e-307, 2.22520559e-306, 7.56599128e-307]],

       [[8.45559303e-307, 8.06612616e-308, 6.89810244e-307],
        [1.22387550e-307, 2.22522596e-306, 8.34423917e-308],
        [9.79107193e-307, 3.33509775e-317, 0.00000000e+000]]])

# Q2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
z=np.zeros((5,5))
v=[1,2,3,4]
z=np.diag(v,-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Q3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
z=np.zeros((8,8),dtype=int)
z[::2,1::2]=1
z[1::2,::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Q4. Normalize a 5x5 random matrix

In [4]:
from math import *
from pylab import *
Z=np.empty((5,5),dtype=int)
print(Z)
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
Z

[[4128860 6029375 3801155 5570652 6619251]
 [7536754 4259932 6357099 6815859 4259932]
 [6357102 7274595 6553710 6029409 6881388]
 [6029410 6881395 6619252 7340077 6488161]
 [6357099 6619239 6029427 4784208      76]]


array([[0.54782545, 0.79999424, 0.50434409, 0.73912883, 0.87826162],
       [1.        , 0.56521666, 0.84347812, 0.90434844, 0.56521666],
       [0.84347852, 0.96521558, 0.86956534, 0.79999875, 0.91304312],
       [0.79999889, 0.91304405, 0.87826175, 0.97390402, 0.86086801],
       [0.84347812, 0.87826002, 0.80000114, 0.63477994, 0.        ]])

# Q5. How to find common values between two arrays?

In [5]:
import numpy as np
array1=[1,2,3,4,5,6]
print("Array1:", array1)
array2=[1,2,3,9,0,8]
print("Array2:", array2)
print("Common Values between two arrays:", np.intersect1d(array1,array2))

Array1: [1, 2, 3, 4, 5, 6]
Array2: [1, 2, 3, 9, 0, 8]
Common Values between two arrays: [1 2 3]


# Q6. How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# Q7. Consider two random array A and B, check if they are equal

In [7]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

equal = np.allclose(A,B)
print(equal)

[0 0 1 0 0]
[1 1 0 1 1]
False


# Q8. Create random vector of size 10 and replace the maximum value by 0

In [8]:
z=np.random.random(10)
print(z)
z[z.argmax()]=0
print(z)

[0.81716846 0.76422594 0.73184083 0.48742509 0.78537745 0.79254191
 0.73966817 0.7586849  0.35648752 0.60760095]
[0.         0.76422594 0.73184083 0.48742509 0.78537745 0.79254191
 0.73966817 0.7586849  0.35648752 0.60760095]


# Q9. How to print all the values of an array?

In [9]:
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Q10. Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")
X = np.random.rand(2, 4)
print(X)
print("\nSubtract the mean of each row of the original matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.27559448 0.097828   0.33760204 0.84444472]
 [0.5165882  0.92138139 0.65442391 0.53566413]]

Subtract the mean of each row of the original matrix:

[[-0.11327283 -0.29103931 -0.05126527  0.45557741]
 [-0.14042621  0.26436699 -0.00259049 -0.12135028]]


# Q11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 3. 3. 2. 2. 3. 3. 2. 2. 5.]


# Q12. How to get the diagonal of a dot product?

In [12]:
A = np.random.randint(0,10,(3,3))
print(A)
B= np.random.randint(0,10,(3,3))
print(B)
#Slow version
C=np.dot(A, B)
print(C)
D=np.diag(C)
print(D)

[[7 4 1]
 [6 0 3]
 [6 1 4]]
[[7 1 3]
 [3 6 8]
 [7 5 4]]
[[68 36 57]
 [63 21 30]
 [73 32 42]]
[68 21 42]


# Q13. How to find the most frequent value in an array

In [13]:
x = np.random.randint(0, 10, 40)
print("Original array:",x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array: [3 8 6 2 2 1 6 7 7 6 4 1 8 3 6 9 9 1 7 2 5 7 2 9 7 0 5 9 1 7 0 5 1 9 6 6 9
 6 7 5]
Most frequent value in the above array:
6


# Q14.How to get the n largest values of an array

In [14]:
import numpy as np
x = np.arange(17)
print("Original array:",x)
z=x.max()
z

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


16

# Q15.How to create a record array from a regular array?

In [15]:
import numpy as np
a1=np.array([5,9,0,6])
a2=np.array(['Black','Yellow','White','Gray'])
a3=np.array([12.20,23,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(5, 'Black', 12.2)
(9, 'Yellow', 23.)
(0, 'White', 20.)
